name: "Bug report"
description: File a Bug
title: '[Issue Title]'
body:
- type: textarea
  attributes:
    label: Issue Description
    description: Please provide a clear and concise description of the issue.
    placeholder: 'Describe the issue...'
  required: true
